SELECT E.ID, COALESCE(CHILD_COUNT,0) AS CHILD_COUNT
FROM ECOLI_DATA E
LEFT JOIN (SELECT COALESCE(PARENT_ID,0) AS ID, COUNT(ID) AS CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID) AS A ON E.ID = A.ID
ORDER BY ID