# SELECT ROUND(AVG(IF(LENGTH <= 10, 10, LENGTH)),2) AS AVERAGE_LENGTH
# FROM FISH_INFO

SELECT
    ROUND(AVG(CASE WHEN LENGTH <= 10 THEN 10
    WHEN LENGTH IS NULL THEN 10
    ELSE LENGTH
    END),2) AS AVERAGE_LENGTH
FROM FISH_INFO