# SELECT *
# FROM (SELECT RI.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
#     FROM REST_INFO RI
#     LEFT JOIN REST_REVIEW RR ON RI.REST_ID = RR.REST_ID) AS A
# WHERE ADDRESS LIKE '서울%' AND SCORE IS NOT NULL
# GROUP BY REST_ID
# ORDER BY SCORE DESC, FAVORITES DESC

SELECT *
FROM (SELECT RI.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
    FROM REST_INFO RI
    LEFT JOIN REST_REVIEW RR ON RI.REST_ID = RR.REST_ID
    WHERE ADDRESS LIKE '서울%'
    GROUP BY REST_ID) AS A
WHERE SCORE IS NOT NULL
ORDER BY SCORE DESC, FAVORITES DESC