WITH D7(DISCOUNT) AS (
    SELECT 1-DISCOUNT_RATE/100
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
        AND DURATION_TYPE LIKE '7%'),
    D30(DISCOUNT) AS (
    SELECT 1-DISCOUNT_RATE/100
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
        AND DURATION_TYPE LIKE '30%'),
    D90(DISCOUNT) AS (
    SELECT 1-DISCOUNT_RATE/100
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
        AND DURATION_TYPE LIKE '90%')
SELECT HISTORY_ID,
    CASE
        WHEN DATEDIFF >= 7 AND DATEDIFF < 30 THEN ROUND(DAILY_FEE * D7.DISCOUNT * DATEDIFF,0)
        WHEN DATEDIFF >= 30 AND DATEDIFF < 90 THEN ROUND(DAILY_FEE * D30.DISCOUNT * DATEDIFF, 0)
        WHEN DATEDIFF >= 90 THEN ROUND(DAILY_FEE * D90.DISCOUNT * DATEDIFF,0)
        ELSE ROUND(DAILY_FEE * DATEDIFF,0)
    END AS FEE
FROM (SELECT HISTORY_ID, DAILY_FEE , DATEDIFF(END_DATE, START_DATE)+1 AS DATEDIFF
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭') A, D7, D30, D90
ORDER BY FEE DESC, HISTORY_ID DESC

# SELECT HISTORY_ID, DATEDIFF,
#     CASE
#         WHEN DATEDIFF >= 7 THEN DAILY_FEE * DISCOUNT_RATE/100 * DATEDIFF

# SELECT *
# FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
# WHERE CAR_TYPE = '트럭'