SELECT FLAVOR
FROM (SELECT J.FLAVOR, SUM(J.TOTAL_ORDER + FH.TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY J
    JOIN FIRST_HALF FH ON J.FLAVOR = FH.FLAVOR
    GROUP BY FLAVOR
    ORDER BY TOTAL_ORDER DESC) AS A
LIMIT 3