SELECT IT.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_TREE IT
LEFT JOIN ITEM_INFO II ON II.ITEM_ID = IT.ITEM_ID
WHERE PARENT_ITEM_ID IN (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE')
ORDER BY IT.ITEM_ID DESC