SELECT E1.YEAR,
        MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV,
        ID
FROM (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, SIZE_OF_COLONY, ID
      FROM ECOLI_DATA) AS E1
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
      MAX(SIZE_OF_COLONY) AS MAX_SIZE
      FROM ECOLI_DATA
      GROUP BY YEAR) AS E2 ON E1.YEAR = E2.YEAR
ORDER BY YEAR, YEAR_DEV