SELECT ID, FISH_NAME, FI.LENGTH
FROM FISH_INFO FI
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE) AS A ON A.FISH_TYPE = FI.FISH_TYPE AND A.LENGTH = FI.LENGTH
JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE