SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES BS
LEFT JOIN BOOK B ON B.BOOK_ID = BS.BOOK_ID
WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '1'
GROUP BY CATEGORY
ORDER BY CATEGORY